# Generated by Django 5.1.5 on 2025-01-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=25)),
                ('admin_email', models.CharField(max_length=25)),
                ('admin_username', models.CharField(max_length=25)),
                ('admin_password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=25)),
                ('instructor_email', models.CharField(max_length=25)),
                ('instructor_username', models.CharField(max_length=25)),
                ('instructor_password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('roadmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('roadmap_title', models.CharField(max_length=25)),
                ('roadmap_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=25)),
                ('student_email', models.CharField(max_length=25)),
                ('student_username', models.CharField(max_length=25)),
                ('student_password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_title', models.CharField(max_length=50)),
                ('ticket_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_instructor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='roadmaps.instructor')),
                ('group_student', models.ManyToManyField(to='roadmaps.student')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.ManyToManyField(to='roadmaps.classgroup')),
                ('project_instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roadmaps.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_name', models.CharField(max_length=75)),
                ('attachment_roadmap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roadmaps.roadmap')),
            ],
        ),
    ]
