# Generated by Django 5.1.5 on 2025-02-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='group_id',
            new_name='class_id',
        ),
    ]
