# Generated by Django 5.1.5 on 2025-01-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='roadmap_students',
            field=models.ManyToManyField(to='roadmaps.student'),
        ),
    ]
