# Generated by Django 5.1.5 on 2025-02-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_roadmap_roadmap_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
