# Generated by Django 5.1.6 on 2025-02-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_rename_group_id_project_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instructor_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
