# Generated by Django 5.1.5 on 2025-02-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0004_remove_project_metadata_roadmap_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_metadata',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='group_join_code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
